# Generated by Django 2.2 on 2020-04-24 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChooseUs',
            new_name='Choose',
        ),
    ]
